### PR TITLE
Optimise form with `react-hook-form`

### PR DESCRIPTION
**Pull request by jsun969**
Hi there, I'm new to the uni and the club.

I found you are using `zod` to validate form so I installed `react-hook-form` to optimise the code which makes the code cleaner and easier to maintain.

`join-us` & `forgot-password` can also be optimised. (which is a huge work XD) In that way, `Form` will not need so many props to set and get state. If you want to do that, please feel free to tell me. I'll be happy to help!

cc @phoenixpereira @rishiad

### CODE REVIEW

**Comment by jsun969** [comment]
need a githook for prettier?

**Comment by jsun969** [comment]
run pnpm i again to enable git hook

**Review by phoenixpereira — APPROVED** [review]
Looks good to me!

**Comment by rishiad** [comment]
LGTM

**Review by rishiad — APPROVED** [review]

**Pull request merged**
