### PR TITLE
feat: Update tech stacks in open source page

### LINKED ISSUE #168: [Feature Request] Update tech stack on open source page
### Overview

Update few tech stacks on open source page

### Details

CourseAPI - Add `Requests`
MyTimeTable - `TypeScript` `React` `Vite` `Pragmatic Drag & Drop` `NextUI` `TailwindCSS`
MyStudyPlan - Change `Next.js` to `Vite`

### Why would this feature be useful?

Let new volunteers know our future projects

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by KnightRadiant44**
### Description
Update few tech stacks on open source page

### Changes Made
Updated the requested tech stacks.

### Related Issues
resolve #168  

### Additional Notes
image

### CODE REVIEW

**Review by jsun969 — CHANGES_REQUESTED** [review]
Please remove the changes in `bump.rdb` `package.json` `pnpm-lock.yaml`

And the tech stack is incorrect from the issue

**Comment by phoenixpereira** [comment]
@KnightRadiant44 The build fails because `pnpm-lock.yaml` is different, so you have to revert the changes done to it to make it work.

**Comment by KnightRadiant44** [comment]
I'll try to revert the changes again after a while

**Comment by phoenixpereira** [comment]
@KnightRadiant44 Try running `pnpm format` since there seems to be some formatting issues in your code. It's not picked up in the formatting check for some reason 🤷‍♂️.

**Comment by KnightRadiant44** [comment]
I will close this pull request and try to resolve this issue first. I am not sure where exactly it is going wrong.

**Comment by rayokamoto** [comment]
Did you run prettier formatting via VS Code? `pnpm format` shouldn't have changed all those files... I was going to suggest closing and redoing the PR but looks like you've already closed it.

In future, make sure to check what files have been changed (`git status`) and only add and commit relevant files to avoid adding things you don't want to add. I also suggest reading the [contributing guidelines](https://github.com/compsci-adl/website/blob/main/CONTRIBUTING.md) for some guidance with formatting and linting, as well as the conventions this project uses for commit messages.

**Pull request closed without merging**
